### ISSUE TITLE
Login with github broken

### ISSUE THREAD

**Issue by kennygrant** [FurqanSoftware/papyrus#1]
Nice project!

I wasn't allowed to log in using a github account - received an Internal Server Error on granting permissions. Managed to get in with a google account.

**Comment by hjr265** [comment]
Hi @kennygrant,

Thank you for reporting the issue. We are looking into it.

**Comment by hjr265** [comment]
Looks like this happens when the GitHub account doesn't have a public email address configured. Our attempt to fix it by just including "user:email" in scope for OAuth wasn't enough.

The package ([gothic](https://github.com/markbates/goth)) that we are using to handle this login mechanism doesn't seem to handle this particular case. It relies on the "email" field and GitHub only sets it when a public email address is configured.

We will have to work around this limitation until it is addressed in gothic.

**Comment by kennygrant** [comment]
Thanks for looking at it, and good work on the project.

**Comment by hjr265** [comment]
@kennygrant Thank you :smile:
